/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface RootsInterface extends utils.Interface {
  contractName: "Roots";
  functions: {
    "getAmountOutClosedForm(uint256,address,uint256,uint256)": FunctionFragment;
    "getAmountOutNewton(uint256,address,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getAmountOutClosedForm",
    values: [BigNumberish, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAmountOutNewton",
    values: [BigNumberish, string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAmountOutClosedForm",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAmountOutNewton",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Roots extends BaseContract {
  contractName: "Roots";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RootsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getAmountOutClosedForm(
      amountIn: BigNumberish,
      tokenIn: string,
      _reserve0: BigNumberish,
      _reserve1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getAmountOutNewton(
      amountIn: BigNumberish,
      tokenIn: string,
      _reserve0: BigNumberish,
      _reserve1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  getAmountOutClosedForm(
    amountIn: BigNumberish,
    tokenIn: string,
    _reserve0: BigNumberish,
    _reserve1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getAmountOutNewton(
    amountIn: BigNumberish,
    tokenIn: string,
    _reserve0: BigNumberish,
    _reserve1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    getAmountOutClosedForm(
      amountIn: BigNumberish,
      tokenIn: string,
      _reserve0: BigNumberish,
      _reserve1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAmountOutNewton(
      amountIn: BigNumberish,
      tokenIn: string,
      _reserve0: BigNumberish,
      _reserve1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getAmountOutClosedForm(
      amountIn: BigNumberish,
      tokenIn: string,
      _reserve0: BigNumberish,
      _reserve1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAmountOutNewton(
      amountIn: BigNumberish,
      tokenIn: string,
      _reserve0: BigNumberish,
      _reserve1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getAmountOutClosedForm(
      amountIn: BigNumberish,
      tokenIn: string,
      _reserve0: BigNumberish,
      _reserve1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAmountOutNewton(
      amountIn: BigNumberish,
      tokenIn: string,
      _reserve0: BigNumberish,
      _reserve1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
